# fly.toml app configuration file generated for maze-runner on 2024-07-31T19:56:29+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maze-runner'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
